replicaCount: 1

image:
  repository: ghcr.io/modernews/alertreport_backend
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2
    memory: 512Mi

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
