name: Release on Version 
on:
  push:
    tags: 
      - "v*"

jobs:
  build-for-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      statuses: read 
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Determine Image Tags
      uses: docker/metadata-action@v5
      id: metadata
      with:
        images: ghcr.io/${{github.repository}}
        tags: |
          latest
          ${{github.ref_name}}
          ${{github.sha}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
